# This is run against builder machines where the common expectation is
# that mongo will be installed on the instance (e.g. Vagrant).

# Note: Stouts.mongodb was being problematic, it was easier/faster to
# just write the tasks needed then to try and fiddle with Stouts to
# get it to work.
- hosts: all
  tasks:
    - name: Add Mongo apt key
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5
      become: yes
      become_user: root

    - name: Add mongo repository to sources list
      apt_repository:
        repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.6 multiverse"
        state: present
      become: yes
      become_user: root

    - name: Update Apt and install mongodb-org
      apt:
        name: mongodb-org
        update_cache: yes
      become: yes
      become_user: root

    - name: Enable the Mongo service
      service:
        name: mongod
        state: started
        enabled: yes
      become: yes
      become_user: root
